spring:
  application:
    name: spring-boot-dubbo-producer
  messages:
    encoding: UTF-8

server:
  port: 9401
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    basedir: ../tomcat/${server.port}

dubbo:
  registry:
    address: zookeeper://192.168.47.128:2181
    timeout: 30000
